# Generated by Django 2.0.7 on 2018-09-13 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songRecommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='played_song',
            old_name='song_id',
            new_name='song_id1',
        ),
        migrations.RemoveField(
            model_name='distance',
            name='songs',
        ),
        migrations.AddField(
            model_name='distance',
            name='song_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_1', to='songRecommender.Song'),
        ),
        migrations.AddField(
            model_name='distance',
            name='song_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_2', to='songRecommender.Song'),
        ),
    ]
